// src/layouts/index.jsx
import React, { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux"
import { useNavigate, useLocation } from "react-router-dom"
import { setUserInfo } from '../store'
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  DownOutlined, SmileOutlined
} from "@ant-design/icons";
import { Outlet } from "react-router-dom";
import { Layout, Menu, Button, theme, Dropdown, Space, Image, message } from "antd";
import { removeToken } from "../libs/util";
import logo from '../logo.svg'
import './index.css'
const { Header, Sider, Content } = Layout;
const LayoutCom = (props) => {
  const [collapsed, setCollapsed] = useState(false);
  const [defaultSelectedKeys, setDefaultSelectedKeys] = useState([])
  const { userInfo, authRouters } = useSelector(state => state.user)
  const dispatch = useDispatch()
  const [menuData, setMenuData] = useState([])
  const navigator = useNavigate()
  const {
    token: { colorBgContainer },
  } = theme.useToken();


  useEffect(() => {
    setDefaultSelectedKeys([window.location.pathname])
  }, [menuData])
  useEffect(() => {
    initMenu()
  }, [authRouters])

  const initMenu = () => {
    const data = traverseTree(authRouters)
    console.log(data)
    setMenuData(data)
  }

  const handJump = (a) => {
    setDefaultSelectedKeys([a.key])
    navigator(a.key)
  }

  // 递归
const traverseTree = (data) => {
    return data.map(item => {
        const newObj = {
            ...item,
            label: item.title,
            key: item.path,
            icon: <UserOutlined />
        }
        if (newObj.children && newObj.children.length) {
            newObj.children = traverseTree(newObj.children)
        }
        return newObj
    })
}

const handleCollapsed = () => {
    setCollapsed((v) => !v)
}

const loginOut = () => {
    dispatch(setUserInfo({}))
    removeToken('userInfo')
    message.success('退出登录成功')
    navigator('/login')
}
  return (
    <div className="layout">
      <Layout style={{ height: '100%', width: '100%' }}>
        <Sider trigger={null} collapsible collapsed={collapsed}>
          <div className="logo">
            <div className="logo">
                 <Image
                        width={50}
                        src={logo}
                    />
                    {
                        !collapsed ? <span>管理系统</span> : null
                    }
            </div>
          </div>
          <Menu
            theme="dark"
            mode="inline"
            selectedKeys={defaultSelectedKeys}
            items={menuData}
            onClick={handJump}
          />
        </Sider>
        <Layout>
          <Header
            style={{
              padding: '0 12px',
              background: colorBgContainer,
              display: 'flex',
              justifyContent: 'space-between'
            }}
          >
            <Button
              type="text"
              icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
              onClick={handleCollapsed}
              style={{
                fontSize: "16px",
                width: 64,
                height: 64,
              }}
            />
            <div className="right">
                <Dropdown
                    menu={{
                        items: [{
                            key: '1',
                            label: (<a onClick={loginOut}>退出登录</a>)
                        }]
                    }}
                >
                    <a onClick={(e) => e.preventDefault()}>
                        <Space>
                            {userInfo.name}
                            <DownOutlined />
                        </Space>
                    </a>
                </Dropdown>
            </div>
          </Header>
          <Content
            style={{
              margin: "24px 16px",
              padding: 24,
              minHeight: 280,
              background: colorBgContainer,
            }}
          >
            <Outlet />
          </Content>
        </Layout>
      </Layout>
    </div>
  );
};
export default LayoutCom;

// src/layouts/index.vue
<template>
  <a-layout class="layout-con">
    <a-layout-sider v-model:collapsed="collapsed" :trigger="null" collapsible>
      <div class="logo">
        <a-image :width="50" src="https://aliyuncdn.antdv.com/vue.png" />
        <span v-if="!collapsed">管理系统</span>
      </div>
      <a-menu
        v-model:selectedKeys="selectedKeys"
        mode="inline"
        theme="dark"
        :inline-collapsed="collapsed"
        :items="menuData"
        @click="handJump"
        ></a-menu>
    </a-layout-sider>
    <a-layout>
      <a-layout-header style="background: #fff;align-items: center; padding: 0 20px;display: flex;justify-content: space-between;">
        <div class="left">
            <MenuFoldOutlined
          v-if="collapsed"
          class="trigger"
          style="font-size: 30px"
          @click="() => (collapsed = !collapsed)"
        />
        <MenuUnfoldOutlined style="font-size: 30px" v-else class="trigger" @click="() => (collapsed = !collapsed)" />
        </div>
        <div class="right">
            <a-dropdown>
                <a class="ant-dropdown-link" @click.prevent>
                {{userInfo.username}}
                <DownOutlined />
                </a>
                <template #overlay>
                    <a-menu>
                        <a-menu-item @click="loginOut">
                            <a href="javascript:;">退出登录</a>
                        </a-menu-item>
                    </a-menu>
                </template>
            </a-dropdown>
        </div>
        
      </a-layout-header>
      <a-layout-content
        :style="{ margin: '24px 16px', padding: '24px', background: '#fff', minHeight: '280px' }"
      >
        <router-view />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>
<script setup>
import {
  MenuFoldOutlined, MenuUnfoldOutlined, DownOutlined, UserOutlined
} from '@ant-design/icons-vue';
import { computed, ref, onMounted, h } from 'vue';
import { useStore } from 'vuex'
import { useRouter, useRoute } from 'vue-router'
import { resetRouter } from '@/router'
import { message } from 'ant-design-vue';
const selectedKeys = ref([]);
const menuData = ref([])
const collapsed = ref(false);
const store = useStore()
const router = useRouter()
const route = useRoute()
const userInfo = computed(() => store.state.userInfo)
const menu = computed(() => store.state.menu)
// 递归
const traverseTree = (data) => {
    return data.map(item => {
        const newObj = {
            ...item,
            label: item.title,
            icon: h(UserOutlined)
        }
        if (newObj.children && newObj.children.length) {
            newObj.children = traverseTree(newObj.children)
        }
        return newObj
    })
}
const initMenu = () => {
    const data = traverseTree(menu.value)
    menuData.value = data
}
const handJump = ({ item }) => {
    router.push(item.path)
}
onMounted(() => {
    selectedKeys.value = [route.meta.key]
    menu.value.length && initMenu()
})
const loginOut = () => {
    store.dispatch('loginOut').then(() => {
    message.success('退出成功')
    resetRouter()
    router.push({ path: '/login' })
})
}
</script>
<style lang="scss" scoped>
.layout-con {
    width: 100%;
    height: 100%;
    .logo {
        text-align: center;
        padding: 5px;
        color: #fff;
    }
}
#components-layout-demo-custom-trigger .trigger {
  font-size: 18px;
  line-height: 64px;
  padding: 0 24px;
  cursor: pointer;
  transition: color 0.3s;
}

#components-layout-demo-custom-trigger .trigger:hover {
  color: #1890ff;
}

#components-layout-demo-custom-trigger .logo {
  height: 32px;
  background: rgba(255, 255, 255, 0.3);
  margin: 16px;
}

.site-layout .site-layout-background {
  background: #fff;
}
</style>
